<?php

  return [

    "timezones" => [
      [ 'id' => "Pacific/Midway", 'name' => "(GMT-11:00) Midway Island, Samoa"],
      [ 'id' => "America/Adak", 'name' => "(GMT-10:00) Hawaii-Aleutian"],
      [ 'id' => "Etc/GMT+10", 'name' => "(GMT-10:00) Hawaii"],
      [ 'id' => "Pacific/Marquesas", 'name' => "(GMT-09:30) Marquesas Islands"],
      [ 'id' => "Pacific/Gambier", 'name' => "(GMT-09:00) Gambier Islands"],
      [ 'id' => "America/Anchorage", 'name' => "(GMT-09:00) Alaska"],
      [ 'id' => "America/Ensenada", 'name' => "(GMT-08:00) Tijuana, Baja California"],
      [ 'id' => "Etc/GMT+8", 'name' => "(GMT-08:00) Pitcairn Islands"],
      [ 'id' => "America/Los_Angeles", 'name' => "(GMT-08:00) Pacific Time (US & Canada)"],
      [ 'id' => "America/Denver", 'name' => "(GMT-07:00) Mountain Time (US & Canada)"],
      [ 'id' => "America/Chihuahua", 'name' => "(GMT-07:00) Chihuahua, La Paz, Mazatlan"],
      [ 'id' => "America/Dawson_Creek", 'name' => "(GMT-07:00) Arizona"],
      [ 'id' => "America/Belize", 'name' => "(GMT-06:00) Saskatchewan, Central America"],
      [ 'id' => "America/Cancun", 'name' => "(GMT-06:00) Guadalajara, Mexico City, Monterrey"],
      [ 'id' => "Chile/EasterIsland", 'name' => "(GMT-06:00) Easter Island"],
      [ 'id' => "America/Chicago", 'name' => "(GMT-06:00) Central Time (US & Canada)"],
      [ 'id' => "America/New_York", 'name' => "(GMT-05:00) Eastern Time (US & Canada)"],
      [ 'id' => "America/Havana", 'name' => "(GMT-05:00) Cuba"],
      [ 'id' => "America/Bogota", 'name' => "(GMT-05:00) Bogota, Lima, Quito, Rio Branco"],
      [ 'id' => "America/Caracas", 'name' => "(GMT-04:30) Caracas"],
      [ 'id' => "America/Santiago", 'name' => "(GMT-04:00) Santiago"],
      [ 'id' => "America/La_Paz", 'name' => "(GMT-04:00) La Paz"],
      [ 'id' => "Atlantic/Stanley", 'name' => "(GMT-04:00) Faukland Islands"],
      [ 'id' => "America/Campo_Grande", 'name' => "(GMT-04:00) Brazil"],
      [ 'id' => "America/Goose_Bay", 'name' => "(GMT-04:00) Atlantic Time (Goose Bay)"],
      [ 'id' => "America/Glace_Bay", 'name' => "(GMT-04:00) Atlantic Time (Canada)"],
      [ 'id' => "America/St_Johns", 'name' => "(GMT-03:30) Newfoundland"],
      [ 'id' => "America/Araguaina", 'name' => "(GMT-03:00) UTC-3"],
      [ 'id' => "America/Montevideo", 'name' => "(GMT-03:00) Montevideo"],
      [ 'id' => "America/Miquelon", 'name' => "(GMT-03:00) Miquelon, St. Pierre"],
      [ 'id' => "America/Godthab", 'name' => "(GMT-03:00) Greenland"],
      [ 'id' => "America/Argentina/Buenos_Aires", 'name' => "(GMT-03:00) Buenos Aires"],
      [ 'id' => "America/Sao_Paulo", 'name' => "(GMT-03:00) Brasilia"],
      [ 'id' => "America/Noronha", 'name' => "(GMT-02:00) Mid-Atlantic"],
      [ 'id' => "Atlantic/Cape_Verde", 'name' => "(GMT-01:00) Cape Verde Is."],
      [ 'id' => "Atlantic/Azores", 'name' => "(GMT-01:00) Azores"],
      [ 'id' => "Europe/Belfast", 'name' => "(GMT) Greenwich Mean Time : Belfast"],
      [ 'id' => "Europe/Dublin", 'name' =>"(GMT) Greenwich Mean Time : Dublin"],
      [ 'id' => "Europe/Lisbon", 'name' =>"(GMT) Greenwich Mean Time : Lisbon"],
      [ 'id' => "Europe/London", 'name' =>"(GMT) Greenwich Mean Time : London"],
      [ 'id' => "Africa/Abidjan", 'name' =>"(GMT) Monrovia, Reykjavik"],
      [ 'id' => "Europe/Amsterdam", 'name' =>"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"],
      [ 'id' => "Europe/Belgrade", 'name' =>"(GMT+01:00)Belgrade, Bratislava, Budapest, Ljubljana, Prague"],
      [ 'id' => "Europe/Brussels", 'name' =>"(GMT+01:00) Brussels, Copenhagen, Madrid, Paris"],
      [ 'id' => "Africa/Algiers", 'name' =>"(GMT+01:00) West Central Africa"],
      [ 'id' => "Africa/Windhoek", 'name' =>"(GMT+01:00) Windhoek"],
      [ 'id' => "Asia/Beirut", 'name' =>"(GMT+02:00) Beirut"],
      [ 'id' => "Africa/Cairo", 'name' =>"(GMT+02:00) Cairo"],
      [ 'id' => "Asia/Gaza", 'name' =>"(GMT+02:00) Gaza"],
      [ 'id' => "Africa/Blantyre", 'name' =>"(GMT+02:00) Harare, Pretoria"],
      [ 'id' => "Asia/Jerusalem", 'name' =>"(GMT+02:00) Jerusalem"],
      [ 'id' => "Europe/Helsinki", 'name' =>"(GMT+02:00) Helsinki"],
      [ 'id' => "Europe/Minsk", 'name' =>"(GMT+02:00) Minsk"],
      [ 'id' => "Asia/Damascus", 'name' =>"(GMT+02:00) Syria"],
      [ 'id' => "Europe/Moscow", 'name' =>"(GMT+03:00) Moscow, St. Petersburg, Volgograd"],
      [ 'id' => "Africa/Addis_Ababa", 'name' =>"(GMT+03:00) Nairobi"],
      [ 'id' => "Asia/Tehran", 'name' =>"(GMT+03:30) Tehran"],
      [ 'id' => "Asia/Dubai", 'name' =>"(GMT+04:00) Abu Dhabi, Muscat"],
      [ 'id' => "Asia/Yerevan", 'name' =>"(GMT+04:00) Yerevan"],
      [ 'id' => "Asia/Kabul", 'name' =>"(GMT+04:30) Kabul"],
      [ 'id' => "Asia/Yekaterinburg", 'name' =>"(GMT+05:00) Ekaterinburg"],
      [ 'id' => "Asia/Tashkent", 'name' =>"(GMT+05:00) Tashkent"],
      [ 'id' => "Asia/Kolkata", 'name' =>"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi"],
      [ 'id' => "Asia/Katmandu", 'name' =>"(GMT+05:45) Kathmandu"],
      [ 'id' => "Asia/Dhaka", 'name' =>"(GMT+06:00) Astana, Dhaka"],
      [ 'id' => "Asia/Novosibirsk", 'name' =>"(GMT+06:00) Novosibirsk"],
      [ 'id' => "Asia/Rangoon", 'name' =>"(GMT+06:30) Yangon (Rangoon)"],
      [ 'id' => "Asia/Bangkok", 'name' =>"(GMT+07:00) Bangkok, Hanoi, Jakarta"],
      [ 'id' => "Asia/Krasnoyarsk", 'name' =>"(GMT+07:00) Krasnoyarsk"],
      [ 'id' => "Asia/Hong_Kong", 'name' =>"(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi"],
      [ 'id' => "Asia/Irkutsk", 'name' =>"(GMT+08:00) Irkutsk, Ulaan Bataar"],
      [ 'id' => "Australia/Perth", 'name' =>"(GMT+08:00) Perth"],
      [ 'id' => "Australia/Eucla", 'name' =>"(GMT+08:45) Eucla"],
      [ 'id' => "Asia/Tokyo", 'name' =>"(GMT+09:00) Osaka, Sapporo, Tokyo"],
      [ 'id' => "Asia/Seoul", 'name' =>"(GMT+09:00) Seoul"],
      [ 'id' => "Asia/Yakutsk", 'name' =>"(GMT+09:00) Yakutsk"],
      [ 'id' => "Australia/Adelaide", 'name' =>"(GMT+09:30) Adelaide"],
      [ 'id' => "Australia/Darwin", 'name' =>"(GMT+09:30) Darwin"],
      [ 'id' => "Australia/Brisbane", 'name' =>"(GMT+10:00) Brisbane"],
      [ 'id' => "Australia/Hobart", 'name' =>"(GMT+10:00) Hobart"],
      [ 'id' => "Asia/Vladivostok", 'name' =>"(GMT+10:00) Vladivostok"],
      [ 'id' => "Australia/Lord_Howe", 'name' =>"(GMT+10:30) Lord Howe Island"],
      [ 'id' => "Etc/GMT-11", 'name' =>"(GMT+11:00) Solomon Is., New Caledonia"],
      [ 'id' => "Asia/Magadan", 'name' =>"(GMT+11:00) Magadan"],
      [ 'id' => "Pacific/Norfolk", 'name' =>"(GMT+11:30) Norfolk Island"],
      [ 'id' => "Asia/Anadyr", 'name' =>"(GMT+12:00) Anadyr, Kamchatka"],
      [ 'id' => "Pacific/Auckland", 'name' =>"(GMT+12:00) Auckland, Wellington"],
      [ 'id' => "Etc/GMT-12", 'name' =>"(GMT+12:00) Fiji, Kamchatka, Marshall Is."],
      [ 'id' => "Pacific/Chatham", 'name' =>"(GMT+12:45) Chatham Islands"],
      [ 'id' => "Pacific/Tongatapu", 'name' =>"(GMT+13:00) Tongatapu"],
      [ 'id' => "Pacific/Kiritimati", 'name' =>"(GMT+14:00) Kiritimati"],
    ]
  ];